platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  RUSTFLAGS: "-D warnings"
  matrix:
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: stable
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: nightly
  install:
  # Rust & Qt
  - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - set PATH=%PATH%;C:\MinGW\bin
  - appveyor DownloadFile https://static.rust-lang.org/rustup/dist/%RUST_INSTALL_TRIPLE%/rustup-init.exe
  - rustup-init.exe -y
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo build --verbose
test_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo test --verbose
